### ISSUE TITLE
Support for Atmega168

### ISSUE THREAD

**Issue by tomrosenback** [christophediericx/ArduinoSketchUploader#9]
Is it possible to add support for the Nano with Atmega168 chip too?

**Comment by christophediericx** [comment]
Thank you for your interest in this library.

One of the evenings later this week, I will verify if I can add support for this. It is likely that it is no problem to do so, although i might not have the corresponding hardware to test (once implemented, it should just work though - the changes required are mostly hardware configuration).

**Comment by tomrosenback** [comment]
Would be great! Tested with NanoR3 and works perfect, would be great to have it working for the 168 aswell. Thanks!

**Comment by christophediericx** [comment]
Support has been added (with the identifier `NanoR2`). 

Could you please try it out? I don't have the relevant hardware myself.

Thanks!

**Comment by tomrosenback** [comment]
Tested and it works! Thank you!!

**Comment by christophediericx** [comment]
Great, thanks for providing feedback!
